[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"

# Ensure environment variables are available during build
[context.production.environment]
  VITE_SUPABASE_URL = ""
  VITE_SUPABASE_ANON_KEY = ""

[context.deploy-preview.environment]
  VITE_SUPABASE_URL = ""
  VITE_SUPABASE_ANON_KEY = ""